-- The schema as Hibernate's ddl-auto=update built it before Flyway took over, so a database from then is
-- baselined past this file (spring.flyway.baseline-on-migrate) and a fresh one gets the same tables.
create table agents (
    id            bigint generated by default as identity primary key,
    owner         varchar(255)  not null,
    name          varchar(255)  not null,
    instructions  varchar(8000) not null,
    others_access varchar(255)  not null check (others_access in ('NONE', 'READ', 'WRITE'))
);

create table agent_mcp_servers (
    id                   bigint generated by default as identity primary key,
    agent_id             bigint        not null references agents (id),
    name                 varchar(255)  not null,
    url                  varchar(255)  not null,
    auth_header          varchar(2000),
    forward_caller_token boolean       not null,
    access               varchar(255)  not null check (access in ('READ', 'WRITE')),
    read_only_tools      varchar(2000),
    unique (agent_id, name)
);

-- A column rather than a foreign key to the agent: the log is read far more than it is joined, and it is
-- deleted with its agent by the service.
create table agent_activity (
    id       bigint generated by default as identity primary key,
    agent_id bigint                      not null,
    at       timestamp(6) with time zone not null,
    kind     varchar(255)                not null,
    detail   varchar(2000)               not null
);
